{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyPiAtoCalZrkvV/mP52iqdv"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","source":["!pip install Cython==0.29.36\n","!pip uninstall scipy -y\n","!pip install scipy==1.9\n","!pip uninstall pyparsing -y\n","!pip install pyparsing==2.4\n","!pip uninstall scikit_learn -y"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"EUm_3KUa6J58","executionInfo":{"status":"ok","timestamp":1733136361641,"user_tz":180,"elapsed":35661,"user":{"displayName":"Pablo Eiterer","userId":"18182467837711484979"}},"outputId":"d3c5a6a8-a3e6-46f7-e750-f8269fb26243"},"execution_count":6,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting Cython==0.29.36\n","  Downloading Cython-0.29.36-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl.metadata (3.1 kB)\n","Downloading Cython-0.29.36-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.9/1.9 MB\u001b[0m \u001b[31m29.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hInstalling collected packages: Cython\n","  Attempting uninstall: Cython\n","    Found existing installation: Cython 3.0.11\n","    Uninstalling Cython-3.0.11:\n","      Successfully uninstalled Cython-3.0.11\n","Successfully installed Cython-0.29.36\n","Found existing installation: scipy 1.14.1\n","Uninstalling scipy-1.14.1:\n","  Successfully uninstalled scipy-1.14.1\n","Collecting scipy==1.9\n","  Downloading scipy-1.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)\n","Collecting numpy<1.25.0,>=1.18.5 (from scipy==1.9)\n","  Downloading numpy-1.24.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)\n","Downloading scipy-1.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m43.9/43.9 MB\u001b[0m \u001b[31m70.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading numpy-1.24.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m17.3/17.3 MB\u001b[0m \u001b[31m136.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hInstalling collected packages: numpy, scipy\n","  Attempting uninstall: numpy\n","    Found existing installation: numpy 2.1.3\n","    Uninstalling numpy-2.1.3:\n","      Successfully uninstalled numpy-2.1.3\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","bigframes 1.27.0 requires scikit-learn>=1.2.2, which is not installed.\n","fastai 2.7.18 requires scikit-learn, which is not installed.\n","imbalanced-learn 0.12.4 requires scikit-learn>=1.0.2, which is not installed.\n","librosa 0.10.2.post1 requires scikit-learn>=0.20.0, which is not installed.\n","mlxtend 0.23.3 requires scikit-learn>=1.3.1, which is not installed.\n","sentence-transformers 3.2.1 requires scikit-learn, which is not installed.\n","shap 0.46.0 requires scikit-learn, which is not installed.\n","sklearn-pandas 2.2.0 requires scikit-learn>=0.23.0, which is not installed.\n","yellowbrick 1.5 requires scikit-learn>=1.0.0, which is not installed.\n","albumentations 1.4.20 requires scipy>=1.10.0, but you have scipy 1.9.0 which is incompatible.\n","jax 0.4.33 requires scipy>=1.10, but you have scipy 1.9.0 which is incompatible.\n","jaxlib 0.4.33 requires scipy>=1.10, but you have scipy 1.9.0 which is incompatible.\u001b[0m\u001b[31m\n","\u001b[0mSuccessfully installed numpy-1.24.4 scipy-1.9.0\n"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["numpy"]},"id":"f1a1db8040c44313917905f5afaf4129"}},"metadata":{}},{"output_type":"stream","name":"stdout","text":["Found existing installation: pyparsing 3.2.0\n","Uninstalling pyparsing-3.2.0:\n","  Successfully uninstalled pyparsing-3.2.0\n","Collecting pyparsing==2.4\n","  Downloading pyparsing-2.4.0-py2.py3-none-any.whl.metadata (1.1 kB)\n","Downloading pyparsing-2.4.0-py2.py3-none-any.whl (62 kB)\n","Installing collected packages: pyparsing\n","  Attempting uninstall: pyparsing\n","    Found existing installation: pyparsing 2.4.7\n","    Uninstalling pyparsing-2.4.7:\n","      Successfully uninstalled pyparsing-2.4.7\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","mlxtend 0.23.3 requires scikit-learn>=1.3.1, which is not installed.\n","yellowbrick 1.5 requires scikit-learn>=1.0.0, which is not installed.\n","httplib2 0.22.0 requires pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2; python_version > \"3.0\", but you have pyparsing 2.4.0 which is incompatible.\n","pydot 3.0.2 requires pyparsing>=3.0.9, but you have pyparsing 2.4.0 which is incompatible.\u001b[0m\u001b[31m\n","\u001b[0mSuccessfully installed pyparsing-2.4.0\n"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["pyparsing"]},"id":"676b82c24ee344c79b9a5158145fd497"}},"metadata":{}},{"output_type":"stream","name":"stdout","text":["\u001b[33mWARNING: Skipping scikit_learn as it is not installed.\u001b[0m\u001b[33m\n","\u001b[0m"]}]},{"cell_type":"code","source":["!pip install scikit-learn==0.24.2 --no-build-isolation"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ZTcNM7gQ6t6r","executionInfo":{"status":"ok","timestamp":1733136406871,"user_tz":180,"elapsed":3343,"user":{"displayName":"Pablo Eiterer","userId":"18182467837711484979"}},"outputId":"700245ee-d65a-4e54-877b-76472c12f542"},"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting scikit-learn==0.24.2\n","  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)\n","  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n","  \n","  \u001b[31m×\u001b[0m \u001b[32mPreparing metadata \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n","  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n","  \u001b[31m╰─>\u001b[0m See above for output.\n","  \n","  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n","  Preparing metadata (pyproject.toml) ... \u001b[?25l\u001b[?25herror\n","\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n","\n","\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n","\u001b[31m╰─>\u001b[0m See above for output.\n","\n","\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n","\u001b[1;36mhint\u001b[0m: See above for details.\n"]}]},{"cell_type":"code","source":["!pip install scikit-learn==0.24.2"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"rfwTX3SS8Tiv","executionInfo":{"status":"ok","timestamp":1733136109060,"user_tz":180,"elapsed":99179,"user":{"displayName":"Pablo Eiterer","userId":"18182467837711484979"}},"outputId":"e1f9a84b-8344-400f-b931-318de07fb5f1"},"execution_count":4,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting scikit-learn==0.24.2\n","  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)\n","  Installing build dependencies ... \u001b[?25l\u001b[?25hdone\n","  Getting requirements to build wheel ... \u001b[?25l\u001b[?25hdone\n","  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n","  \n","  \u001b[31m×\u001b[0m \u001b[32mPreparing metadata \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n","  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n","  \u001b[31m╰─>\u001b[0m See above for output.\n","  \n","  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n","  Preparing metadata (pyproject.toml) ... \u001b[?25l\u001b[?25herror\n","\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n","\n","\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n","\u001b[31m╰─>\u001b[0m See above for output.\n","\n","\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n","\u001b[1;36mhint\u001b[0m: See above for details.\n"]}]},{"cell_type":"code","source":["!pip install auto-sklearn==0.14.7\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"iiteQheN8UJd","executionInfo":{"status":"ok","timestamp":1733136223983,"user_tz":180,"elapsed":99126,"user":{"displayName":"Pablo Eiterer","userId":"18182467837711484979"}},"outputId":"29aefe32-0b37-41a9-e949-cc190654c014"},"execution_count":5,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting auto-sklearn==0.14.7\n","  Downloading auto-sklearn-0.14.7.tar.gz (6.4 MB)\n","\u001b[?25l     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/6.4 MB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.4/6.4 MB\u001b[0m \u001b[31m58.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from auto-sklearn==0.14.7) (75.1.0)\n","Requirement already satisfied: typing_extensions in /usr/local/lib/python3.10/dist-packages (from auto-sklearn==0.14.7) (4.12.2)\n","Requirement already satisfied: distro in /usr/local/lib/python3.10/dist-packages (from auto-sklearn==0.14.7) (1.9.0)\n","Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from auto-sklearn==0.14.7) (2.1.3)\n","Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from auto-sklearn==0.14.7) (1.14.1)\n","Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from auto-sklearn==0.14.7) (1.4.2)\n","Collecting scikit-learn<0.25.0,>=0.24.0 (from auto-sklearn==0.14.7)\n","  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)\n","  Installing build dependencies ... \u001b[?25l\u001b[?25hdone\n","  Getting requirements to build wheel ... \u001b[?25l\u001b[?25hdone\n","  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n","  \n","  \u001b[31m×\u001b[0m \u001b[32mPreparing metadata \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n","  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n","  \u001b[31m╰─>\u001b[0m See above for output.\n","  \n","  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n","  Preparing metadata (pyproject.toml) ... \u001b[?25l\u001b[?25herror\n","\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n","\n","\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n","\u001b[31m╰─>\u001b[0m See above for output.\n","\n","\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n","\u001b[1;36mhint\u001b[0m: See above for details.\n"]}]},{"cell_type":"code","source":[],"metadata":{"id":"186UEWXZ9oo3"},"execution_count":null,"outputs":[]}]}